version: '3.3'
services:
  db:
    image: leaguemysql:1.0
    #    volumes:
    #      - ./mysql-init-files/:/docker-entrypoint-initdb.d/
    restart: always
    container_name: leaguemysql
    environment:
      - ENV MYSQL_ROOT_PASSWORD="1234"
    ports:
      - '3333:3306'
    expose:
      - '3333'